@Api_HostAddress = https://localhost:7175

### key: Client Endpoints

GET {{Api_HostAddress}}/api/Client
Accept: application/json

###GetId
GET {{Api_HostAddress}}/api/Client/1
Accept: application/json

###Create

POST {{Api_HostAddress}}/api/Client/Add-Client
Content-Type: application/json
{
   "FirstName": "riad",
 "LastName": "derrar",
 "Email": "derrar.dome@example.com",
 "Job": "info",
 "PhoneNumber": "123-456-7890",
 "Second_PhoneNumber": "098-765-4321",
 "Third_PhoneNumber": null,
 "IdCard_Number": "ID1456",
 "Passport_Number": "P1298789"
}

### edit
POST {{Api_HostAddress}}/api/Client/3
Content-Type: application/json

###
DELETE {{Api_HostAddress}}/api/Client/6
Content-Type: application/json
