@Api_HostAddress = https://localhost:7175

GET {{Api_HostAddress}}/weatherforecast/
Accept: application/json

### key: User Endpoints
GET {{Api_HostAddress}}/api/User/
Accept: application/json
###
GET {{Api_HostAddress}}/api/User/5
Accept: application/json

### 
GET {{Api_HostAddress}}/User/search
Accept: application/json

### key: Create User
POST {{Api_HostAddress}}/api/User
Content-Type: application/json
{
 "FirstName": "John",
 "LastName": "Doe",
 "Email": "john.doe@example.com",
 "Password": "123",
 "PhoneNumber": "123-456-7890",
 "Second_PhoneNumber": "098-765-4321",
 "Third_PhoneNumber": null,
 "IdCard_Number": "ID123456",
 "Passport_Number": "P123456789"
}

### key: Edit User
POST {{Api_HostAddress}}/User/5
Content-Type: application/json

###
DELETE {{Api_HostAddress}}/User/3
Content-Type: application/json
